### ISSUE TITLE
error when running docker build on mac os (Apple silicon)

### ISSUE THREAD

**Issue by apeshimam** [benman1/generative_ai_with_langchain#20]
`Dockerfile:10
--------------------
   9 |
  10 | >>> RUN wget \
  11 | >>>     https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
  12 | >>>     && mkdir /root/.conda \
  13 | >>>     && bash Miniconda3-latest-Linux-x86_64.sh -b \
  14 | >>>     && rm -f Miniconda3-latest-Linux-x86_64.sh
  15 |
--------------------
ERROR: failed to solve: process "/bin/sh -c wget     https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh     && mkdir /root/.conda     && bash Miniconda3-latest-Linux-x86_64.sh -b     && rm -f Miniconda3-latest-Linux-x86_64.sh" did not complete successfully: exit code: 133`

**Comment by benman1** [comment]
@apeshimam That's a bit hard to debug without more output, but it seems the miniconda installation didn't work. If you start from a Miniconda image instead of Ubuntu this could work better. I've pushed a change to the Dockerfile. Please let me know what happens when you build after downloading/pulling this change.
