### ISSUE TITLE
Conda env  create Failed

### ISSUE THREAD

**Issue by harjitssandhu** [benman1/generative_ai_with_langchain#3]
Conda command to create new environment with dependencies failed. Please check below error. It seems to have failed downloading and installing ray (second last items in the langchain_ai.yaml file. 

Relevant trace is provided below.

"Collecting ray[serve]>=2.6.3 (from -r /Users/harjitsinghsandhu/generative_ai_with_langchain/condaenv.2d2gaf81.requirements.txt (line 28))
  Downloading ray-2.7.0-cp310-cp310-macosx_10_15_x86_64.whl (63.2 MB)
     ━━━━━━━━━━━━━━━━╸                        26.7/63.2 MB 292.6 kB/s eta 0:02:05

Pip subprocess error:
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    ray[serve]>=2.6.3 from https://files.pythonhosted.org/packages/37/bc/02600626039ad6596ced511c52de9bab6a22811a607fe5783bee839a2c59/ray-2.7.0-cp310-cp310-macosx_10_15_x86_64.whl"

**Comment by benman1** [comment]
Hi @harjitssandhu!
Thanks for trying out the installation. According to your description title this is a failure with conda, but the limited trace that you provide seems to point at a pip installation. Which one is it?

I've spent some time trying this out just to find that the conda installation seems to work fine as it is. You are actually not providing any commands or a sufficiently long terminal output to figure out the commands you've entered nor is that part of your description. This would be very useful information in case you need help. Since the conda command mentioned in the README works, it seems that we can close this issue. Please let me know any clarifying information.
